### ISSUE TITLE
How to retrieve a global object

### ISSUE THREAD

**Issue by brunano21** [ng-web-apis/universal#11]
Hi,

I'm not even sure if this is the right place to ask this, but I'm struggling for a while so I thought to ask hoping to get some assistance. I'm new to Angular Universal. 

I'm facing a simple issue when using [mixpanel.js](https://developer.mixpanel.com/docs/javascript-quickstart#installation-option-2-html). I have added that snippet in the link here into my `index.html`. My server.ts looks clean so far, as it was originally created by the Universal schematic.
Then into a service (let's say `mixpanel.service`), I'm trying to access the `mixpanel` object but I'm getting an `undefined value` all the times. In the service, I have injected the document as `@Inject(WINDOW) window: Window` and trying to get a reference to the mixpanel object with `this.window['mixpanel']`. 

Any help or idea what's wrong?

**Comment by waterplea** [comment]
It is an issue with mixpanel.js setting things on `window`. I'm not sure you can befriend this library and SSR, probably best idea is to not add it on the server side and hide away what it is supposed to to behind some ngIf and loading animation or something. Anyway, this is unrelated to this library so closing this issue.
