### ISSUE TITLE
return null for first time

### ISSUE THREAD

**Issue by torokmakto** [ng-web-apis/universal#14]
hello and thanks for nice article.
when i using universal package its return local storage not defined why?
i add UNIVERSAL_LOCAL_STORAGE in app.server.module.ts same as document and when i using that with injecting common package its return null in terminal but i get console.log of my token in browser console and its continue with request again and for second time i get respond of server why its happen?

**Comment by waterplea** [comment]
Hi @torokmakto. It's working fine for me. Can you provide a reproduction?
