### ISSUE TITLE
Module not found: Error: Can't resolve 'perf_hooks'

### ISSUE THREAD

**Issue by Teebo** [ng-web-apis/universal#17]
# 🐞 Bug report

### Description

I am working on the issue of providing tokens in the server for universal pre-render.
I thought instead of providing the tokens in the server module, it makes sense to use the app module.
I have provided them like below.

```
import {
  UNIVERSAL_LOCATION,
  UNIVERSAL_USER_AGENT,
} from '@ng-web-apis/universal';

...

    {
      provide: UNIVERSAL_USER_AGENT,
      useValue: '',
    },
    {
      provide: UNIVERSAL_LOCATION,
      useValue: '',
    },

```

This seems to lead some where... to an error: 

`./node_modules/@ng-web-apis/universal/__ivy_ngcc__/fesm2015/ng-web-apis-universal.js:457:9-42 - Error: Module not found: Error: Can't resolve 'perf_hooks' in 'C:\Users\Thabo-Zyberfox\Development\sa-places-web\node_modules\@ng-web-apis\universal\__ivy_ngcc__\fesm2015'`

Any ideas how to resolve this error?
### Reproduction

http://www.stackblitz.com/...

### Versions

`"@ng-web-apis/universal": "^1.12.0",`
`Angular 13`

### Additional context

Could be related to [issue](https://github.com/nodejs/node/issues/28635)

Maybe check if it is the browser and provide the window [performance](https://github.com/ng-web-apis/universal/blob/7e8b6d102b46be3777f70e682a216ba819a94382/projects/universal/src/constants/universal-performance.ts)?

**Comment by waterplea** [comment]
You are not supposed to use server side tokens on client side modules, client side works as is because of factories for tokens and uses window.performance.
