### ISSUE TITLE
Support for Web Audio API for audio playback

### ISSUE THREAD

**Issue by mann1996** [ng-web-apis/universal#4]
# 🚀 Feature request

### Is your feature request related to a problem?
Currently I am on music streaming project and I have used Web Audio API to play audio which is working fine on CSR
For improving seo I decided to switch to Angular Universal for SSR but Audio object is not defined in Node.js and I have n idea how to solve this problem.
### Describe the solution you'd like
If its possible to add web audio api support for this package, it would be very helpful

**Comment by waterplea** [comment]
Hi @mann1996 

Are you using our library to work with Web Audio API? This one:
https://github.com/ng-web-apis/audio

I'm not sure there's much that can be done to ease SSR for Web Audio API. All those classes are just not defined on Node.js side.  The best you can do is just add type-safe fallbacks so no errors are thrown, but there's a lot of classes there. It might be best to just hide those components/directives behind *ngIf for browser side if it's possible. Can you tell us more about your project?

**Comment by mann1996** [comment]
Got it working by using browser check and using ngif to hide component on server side
