### ISSUE TITLE
[BUG] URL is not defined

### ISSUE THREAD

**Issue by 6matko** [ng-web-apis/universal#8]
# 🐞 Bug report

### Description

Added your library but experienced a bug specifically on Azure. On localhost everything works fine. Following error is displayed in Azure console:
> ReferenceError: URL is not definedat Object.provideLocation

After removing `provideLocation(req),` everything worked fine on Azure as well
### Reproduction

Add `provideLocation(req),` to server.ts and preferably deploy to Azure.
I have following code, but a little bit shortened:
```typescript
res.render(
      'index',
      {
        req,
        providers: [
          { provide: APP_BASE_HREF, useValue: req.baseUrl },
          provideLocation(req),
          provideUserAgent(req),
        ]
      }
    );

```
### Expected behavior

App is not throwing error, especially when hosted on Azure.

### Versions

Angular: 9.1.6
Angular universal: 9.1.1

### Additional context
I dont know if its related but when searched for answers then found similar issue in @angular/universal github that was opened 3 days ago: https://github.com/angular/universal/issues/1974 (Fix here: https://github.com/angular/universal/pull/1975/commits/dacde00426305124ab8537ec7ff4a74f1a9b2a6a). This issue is fixed universal version 1.11.2 and if I am not mistaking then I would have to update Angular as well in order to get that version but updating Angular is not an option for me right now. Maybe similar fix would solve this issue as well.

**Comment by waterplea** [comment]
Hello! Thank you for your interest in our library :) What Node.js version are you using on Azure? I see here that `new URL` became available since version 10:
https://nodejs.org/docs/latest-v10.x/api/url.html

**Comment by 6matko** [comment]
Seems like v8.9.4. Thanks for a hint. Will try to change it tomorrow :)

**Comment by 6matko** [comment]
Yes. Issue was in Node.js version that was used on Azure. Set it to 10+ and everything works fine. Thank you for quick response :)
